const tableData = [
  {
    sNo: 1,
    company: "Adobe",
    qualifications: "All B.Tech",
    package: "45 LPA",
  },
  {
    sNo: 2,
    company: "Trilogy",
    qualifications: "B.Tech CSE,BCA,MCA",
    package: "36.9 LPA",
  },
  {
    sNo: 3,
    company: "Freshworks",
    qualifications: "MBA",
    package: "25 LPA",
  },
  {
    sNo: 4,
    company: "Ebullient Securities",
    qualifications: "MBA,BBA",
    package: "23 LPA",
  },
  {
    sNo: 5,
    company: "BNM Solutions",
    qualifications: "BBA",
    package: "25 LPA",
  },
  {
    sNo: 6,
    company: "TCS",
    qualifications: "CSE",
    package: "15 LPA",
  },
  {
    sNo: 7,
    company: "Josh Technology",
    qualifications: "CSE",
    package: "14.23 LPA",
  },
  {
    sNo: 8,
    company: "Boon",
    qualifications: "MBA,BBA",
    package: "12 LPA",
  },
  {
    sNo: 9,
    company: "Acxiom Consulting",
    qualifications: "BCA,MCA",
    package: "10 LPA",
  },
  {
    sNo: 10,
    company: "Centilytics",
    qualifications: "MBA",
    package: "10 LPA",
  },
  {
    sNo: 11,
    company: "Jio",
    qualifications: "CSE",
    package: "10 LPA",
  },
  {
    sNo: 12,
    company: "Prism Cement",
    qualifications: "MBA",
    package: "9.5 LPA",
  },
  {
    sNo: 13,
    company: "Talbros",
    qualifications: "CSE",
    package: "9 LPA",
  },
  {
    sNo: 14,
    company: "Remotestate",
    qualifications: "BCA",
    package: "8.5 LPA",
  },
  {
    sNo: 15,
    company: "Great Developer",
    qualifications: "MBA",
    package: "8.36 LPA",
  },
  {
    sNo: 16,
    company: "Ocubes",
    qualifications: "MBA",
    package: "8 LPA",
  },
  {
    sNo: 17,
    company: "Quantum It Soltions",
    qualifications: "MBA",
    package: "8 LPA",
  },
  {
    sNo: 18,
    company: "Thinksys",
    qualifications: "BCA",
    package: "8 LPA",
  },
  {
    sNo: 19,
    company: "NS3TechSolutions Private Limited",
    qualifications: "B.Com,BBA & MBA",
    package: "7.5 LPA",
  },
  {
    sNo: 20,
    company: "Shree Cement",
    qualifications: "B.Tech CSE",
    package: "7 LPA",
  },
  {
    sNo: 21,
    company: "Lenskart",
    qualifications: "BAJMC",
    package: "7 LPA",
  },
  {
    sNo: 22,
    company: "Hoping Minds",
    qualifications: "MB",
    package: "7 LPA",
  },
  {
    sNo: 23,
    company: "Anytech Meta",
    qualifications: "MBA",
    package: "7 LPA",
  },
  {
    sNo: 24,
    company: "ICICI Bank",
    qualifications: "Btech CS/IT/MCA/BCA",
    package: "7 LPA",
  },
  {
    sNo: 25,
    company: "Kozent Tec Pvt. Ltd",
    qualifications: "BBA,Mba",
    package: "7 LPA",
  },
  {
    sNo: 26,
    company: "University Living",
    qualifications: "BCA",
    package: "7 LPA",
  },
  {
    sNo: 27,
    company: "GENPACT",
    qualifications: "B.Tech CSE",
    package: "6.8 LPA",
  },
  {
    sNo: 28,
    company: "Nirvana Soluation",
    qualifications: "MBA & BBA",
    package: "6.8 LPA",
  },
  {
    sNo: 29,
    company: "Creative Buffer",
    qualifications: "B.Tech CSE",
    package: "6.7 LPA",
  },
  {
    sNo: 30,
    company: "Intractive Broker",
    qualifications: "BBA",
    package: "6.68 LPA",
  },
  {
    sNo: 31,
    company: "Cvent",
    qualifications: "CSE",
    package: "6.63 LPA",
  },
  {
    sNo: 32,
    company: "Fin Cart",
    qualifications: "BBA",
    package: "6.6 LPA",
  },
  {
    sNo: 33,
    company: "Penthara Technologies",
    qualifications: "BBA",
    package: "6.6 LPA",
  },
  {
    sNo: 34,
    company: "Credflow",
    qualifications: "MBA",
    package: "6.5 LPA",
  },
  {
    sNo: 35,
    company: "Corizo",
    qualifications: "MBA",
    package: "6.5 LPA",
  },
  {
    sNo: 36,
    company: "Planetspark",
    qualifications: "MBA",
    package: "6.5 LPA",
  },
  {
    sNo: 37,
    company: "Plnetspark",
    qualifications: "BAJMC",
    package: "6.5 LPA",
  },
  {
    sNo: 38,
    company: "MoneyKarma",
    qualifications: "Agriculture",
    package: "6.5 LPA",
  },
  {
    sNo: 39,
    company: "TechBridge Consultancy Services Pvt. Ltd",
    qualifications: "B. Tech",
    package: "6.5 LPA",
  },
  {
    sNo: 40,
    company: "OneBanc Technologies Private Limited",
    qualifications: "BBA",
    package: "6.4 LPA",
  },
  {
    sNo: 41,
    company: "Seeds Fincap Pvt. Ltd.",
    qualifications: "B.Tech CSE , MBA & BBA",
    package: "6.3 LPA",
  },
  {
    sNo: 42,
    company: "Pantheon Digital Private Limited",
    qualifications: "BCA, MCA ,B.Tech CSE",
    package: "6.2 LPA",
  },
  {
    sNo: 43,
    company: "Agrostar Agriculture",
    qualifications: "Agri",
    package: "6 LPA",
  },
  {
    sNo: 44,
    company: "Skillkskart",
    qualifications: "MBA",
    package: "6 LPA",
  },
  {
    sNo: 45,
    company: "Defacto Infotech",
    qualifications: "CSE",
    package: "6 LPA",
  },
  {
    sNo: 46,
    company: "Exovate Ventures",
    qualifications: "BBA",
    package: "6 LPA",
  },
  {
    sNo: 47,
    company: "Chicmic",
    qualifications: "CSE",
    package: "6 LPA",
  },
  {
    sNo: 48,
    company: "Extramarks",
    qualifications: "BAJMC",
    package: "6 LPA",
  },
  {
    sNo: 49,
    company: "Grazitti Interactive",
    qualifications: "MBA",
    package: "6 LPA",
  },
  {
    sNo: 50,
    company: "Hexaware Technologies",
    qualifications: "CSE",
    package: "6 LPA",
  },
    {
    sNo: 51,
    company: "Extramarks",
    qualifications: "BAJMC",
    package: "6 LPA",
  },
  {
    sNo: 52,
    company: "Grazitti Interactive",
    qualifications: "MBA",
    package: "6 LPA",
  },
  {
    sNo: 53,
    company: "Hexaware Technologies",
    qualifications: "CSE",
    package: "6 LPA",
  },
  {
    sNo: 54,
    company: "Realty Smartz",
    qualifications: "MBA",
    package: "6 LPA",
  },
  {
    sNo: 55,
    company: "RNF Technologies",
    qualifications: "MBA",
    package: "6 LPA",
  },
  {
    sNo: 56,
    company: "Skill Vertex",
    qualifications: "CSE",
    package: "6 LPA",
  },
  {
    sNo: 57,
    company: "(Vizva Consultancy Services) SilverSpace Inc.",
    qualifications: "B.Tech CSE",
    package: "6 LPA",
  },
  {
    sNo: 58,
    company: "Berger Paints Limited",
    qualifications: "B.Tech Civil",
    package: "6 LPA",
  },
  {
    sNo: 59,
    company: "G&CC Management Services Pvt. Ltd.",
    qualifications: "BCA & MCA",
    package: "6 LPA",
  },
  {
    sNo: 60,
    company: "Restroworks (Formerly Posist)",
    qualifications: "BCA & MCA",
    package: "6 LPA",
  },
  {
    sNo: 61,
    company: "Techolution India Pvt Ltd",
    qualifications: "B.Tech CSE",
    package: "6 LPA",
  },
  {
    sNo: 62,
    company: "Triple minds",
    qualifications: "BCA",
    package: "6 LPA",
  },
  {
    sNo: 63,
    company: "Unlox academy",
    qualifications: "BBA",
    package: "6 LPA",
  },
  {
    sNo: 64,
    company: "VRAIO SOFTWARE SOLUTIONS PVT LTD",
    qualifications: "MBA",
    package: "6 LPA",
  },
  {
    sNo: 65,
    company: "Chetu",
    qualifications: "B.Tech CSE",
    package: "5.9 LPA",
  },
  {
    sNo: 66,
    company: "Quadrafort Technologies Ltd",
    qualifications: "MBA",
    package: "5.9 LPA",
  },
  {
    sNo: 67,
    company: "24/7 Software",
    qualifications: "B.Tech CSE",
    package: "5.7 LPA",
  },
  {
    sNo: 68,
    company: "Truelancer",
    qualifications: "MBA",
    package: "5.68 LPA",
  },
  {
    sNo: 69,
    company: "Seeds Fincap Pvt. Ltd. Agriculture",
    qualifications: "Agri",
    package: "5.6 LPA",
  },
  {
    sNo: 70,
    company: "MWIDM INC",
    qualifications: "BAJMC",
    package: "5.6 LPA",
  },
  {
    sNo: 71,
    company: "DhanGuard",
    qualifications: "B.Sc Agriculture",
    package: "5.6 LPA",
  },
  {
    sNo: 72,
    company: "Navyug Infosolution Pvt ltd",
    qualifications: "BCA, MCA",
    package: "5.5 LPA",
  },
  {
    sNo: 73,
    company: "AgroStar",
    qualifications: "Agriculture",
    package: "5.4 LPA",
  },
  {
    sNo: 74,
    company: "BizDateUp Technologies Pvt Ltd",
    qualifications: "BBA, MBA & B.com",
    package: "5.2 LPA",
  },
  {
    sNo: 75,
    company: "Oodles Technology",
    qualifications: "BBA,Mass Media",
    package: "5.2 LPA",
  },
  {
    sNo: 76,
    company: "Ceasefire",
    qualifications: "BCA",
    package: "5.16 LPA",
  },
  {
    sNo: 77,
    company: "Revvlocoty",
    qualifications: "MBA",
    package: "5 LPA",
  },
  {
    sNo: 78,
    company: "Black Olive",
    qualifications: "BAJMC",
    package: "5 LPA",
  },
  {
    sNo: 79,
    company: "Vaco Binary",
    qualifications: "MBA (Finance)",
    package: "5 LPA",
  },
  {
    sNo: 80,
    company: "Continuum Global",
    qualifications: "BAJMC",
    package: "5 LPA",
  },
  {
    sNo: 81,
    company: "Vayuz",
    qualifications: "B.Tech CSE & AIML",
    package: "5 LPA",
  },
  {
    sNo: 82,
    company: "24/7 Software",
    qualifications: "BCA",
    package: "5 LPA",
  },
  {
    sNo: 83,
    company: "Aloha Technology",
    qualifications: "CSE",
    package: "5 LPA",
  },
  {
    sNo: 84,
    company: "ASC International",
    qualifications: "CSE",
    package: "5 LPA",
  },
  {
    sNo: 85,
    company: "HikeEdu",
    qualifications: "BAJMC",
    package: "5 LPA",
  },
  {
    sNo: 86,
    company: "HNJ Infra",
    qualifications: "BBA",
    package: "5 LPA",
  },
  {
    sNo: 87,
    company: "Khanna Paper Mills",
    qualifications: "MBA",
    package: "5 LPA",
  },
  {
    sNo: 88,
    company: "Merkle Sokarti",
    qualifications: "CSE",
    package: "5 LPA",
  },
  {
    sNo: 89,
    company: "Raftaar",
    qualifications: "BAJMC",
    package: "5 LPA",
  },
  {
    sNo: 90,
    company: "Virtous",
    qualifications: "B.Tech CSE",
    package: "5 LPA",
  },
  {
    sNo: 91,
    company: "Fare portal",
    qualifications: "MBA",
    package: "5 LPA",
  },
  {
    sNo: 92,
    company: "Hunger Box",
    qualifications: "MBA",
    package: "5 LPA",
  },
  {
    sNo: 93,
    company: "RKC Infrabuilt Pvt. Ltd.",
    qualifications: "B.Tech ME, CE, ECE",
    package: "5 LPA",
  },
  {
    sNo: 94,
    company: "Univia Pvt. Ltd.",
    qualifications: "BAJMC",
    package: "5 LPA",
  },
  {
    sNo: 95,
    company: "wiggle media",
    qualifications: "MBA",
    package: "5 LPA",
  },
  {
    sNo: 96,
    company: "Root Analysis",
    qualifications: "CSE",
    package: "4.9 LPA",
  },
  {
    sNo: 97,
    company: "Cronj IT",
    qualifications: "BCA",
    package: "4.8 LPA",
  },
  {
    sNo: 98,
    company: "coding Ninjas",
    qualifications: "B.Tech CSE",
    package: "4.8 LPA",
  },
  {
    sNo: 99,
    company: "Easyecom",
    qualifications: "BBA",
    package: "4.7 LPA",
  },
  {
    sNo: 100,
    company: "Netsmartz",
    qualifications: "BAJMC",
    package: "4.6 LPA",
  },
    {
    sNo: 101,
    company: "CLOUD ANALOGY",
    qualifications: "B.Tech CSE",
    package: "4.6 LPA",
  },
  {
    sNo: 102,
    company: "DAMSUN INDIA",
    qualifications: "CIVIL",
    package: "4.6 LPA",
  },
  {
    sNo: 103,
    company: "Code Brew Labs",
    qualifications: "BCA",
    package: "4.5 LPA",
  },
  {
    sNo: 104,
    company: "Leadsconnect",
    qualifications: "BCA",
    package: "4.5 LPA",
  },
  {
    sNo: 105,
    company: "Fusionpact",
    qualifications: "B.Tech CSE",
    package: "4.5 LPA",
  },
  {
    sNo: 106,
    company: "Phronesis Partners",
    qualifications: "BAJMC",
    package: "4.5 LPA",
  },
  {
    sNo: 107,
    company: "Prodesk IT",
    qualifications: "BCA",
    package: "4.5 LPA",
  },
  {
    sNo: 108,
    company: "Axis Bank Limited",
    qualifications: "BAJMC",
    package: "4.5 LPA",
  },
  {
    sNo: 109,
    company: "Nucleus Software",
    qualifications: "CSE",
    package: "4.33 LPA",
  },
  {
    sNo: 110,
    company: "Shine Design Pvt Ltd",
    qualifications: "MBA",
    package: "4.2 LPA",
  },
  {
    sNo: 111,
    company: "Wits Innovation LAb",
    qualifications: "MCA",
    package: "4.2 LPA",
  },
  {
    sNo: 112,
    company: "Calvin Klein and Tommy Hilfiger",
    qualifications: "BAJMC",
    package: "4 LPA",
  },
  {
    sNo: 113,
    company: "Act 21",
    qualifications: "MBA",
    package: "4 LPA",
  },
  {
    sNo: 114,
    company: "Escalon",
    qualifications: "BAJMC",
    package: "4 LPA",
  },
  {
    sNo: 115,
    company: "LTI Mindtree",
    qualifications: "CSE",
    package: "4 LPA",
  },
  {
    sNo: 116,
    company: "Mamsys",
    qualifications: "MBA",
    package: "4 LPA",
  },
  {
    sNo: 117,
    company: "Matrix Geo",
    qualifications: "BAJMC",
    package: "4 LPA",
  },
  {
    sNo: 118,
    company: "Sopra Steria",
    qualifications: "BCA",
    package: "4 LPA",
  },
  {
    sNo: 119,
    company: "Upgrad",
    qualifications: "MBA",
    package: "4 LPA",
  },
  {
    sNo: 120,
    company: "VVDN",
    qualifications: "BCA",
    package: "4 LPA",
  },
  {
    sNo: 121,
    company: "Step2Gen Technologies",
    qualifications: "CSE",
    package: "3.8 LPA",
  },
  {
    sNo: 122,
    company: "Omninos Solutions",
    qualifications: "MBA",
    package: "3.8 LPA",
  },
  {
    sNo: 123,
    company: "Kent",
    qualifications: "BAJMC",
    package: "3.8 LPA",
  },
  {
    sNo: 124,
    company: "Indus Valley Partners",
    qualifications: "BCA",
    package: "3.8 LPA",
  },
  {
    sNo: 125,
    company: "Collabera",
    qualifications: "BAJMC",
    package: "3.7 LPA",
  },
  {
    sNo: 126,
    company: "U Certify",
    qualifications: "BBA & MBA",
    package: "3.6 LPA",
  },
  {
    sNo: 127,
    company: "AiHifusion",
    qualifications: "B.Tech CSE",
    package: "3.5 LPA",
  },
  {
    sNo: 128,
    company: "Sprintm Technologies Agriculture",
    qualifications: "Agri",
    package: "3 LPA",
  },
  {
    sNo: 129,
    company: "Adsrole",
    qualifications: "BAJMC",
    package: "3 LPA",
  },
  {
    sNo: 130,
    company: "AlgoCirrus",
    qualifications: "CSE",
    package: "3 LPA",
  },
  {
    sNo: 131,
    company: "Anviam",
    qualifications: "BCA",
    package: "3 LPA",
  },
  {
    sNo: 132,
    company: "Bayone",
    qualifications: "MBA",
    package: "3 LPA",
  },
  {
    sNo: 133,
    company: "Celeb AI",
    qualifications: "BCA",
    package: "3 LPA",
  },
  {
    sNo: 134,
    company: "Mobiloitte",
    qualifications: "MBA",
    package: "3 LPA",
  },
  {
    sNo: 135,
    company: "Muvro Technologies",
    qualifications: "BCA",
    package: "3 LPA",
  },
  {
    sNo: 136,
    company: "Software House",
    qualifications: "CSE",
    package: "3 LPA",
  },
  {
    sNo: 137,
    company: "Sugam Group",
    qualifications: "BAJMC",
    package: "3 LPA",
  },
  {
    sNo: 138,
    company: "Tommy Hilfiger-Calvin Klein",
    qualifications: "MBA",
    package: "3 LPA",
  },
  {
    sNo: 139,
    company: "Wipro",
    qualifications: "MBA, B.Com,BBA",
    package: "3 LPA",
  },
];

export default tableData;